---
- name: Prepare Target Node for Kubernetes
  hosts: target
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install MicroK8s
      snap:
        name: microk8s
        classic: yes

    - name: Add 'ubuntu' user to groups
      user:
        name: ubuntu
        groups: docker, microk8s
        append: yes

    - name: Ensure .kube directory exists
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Wait for MicroK8s to be ready
      shell: microk8s status --wait-ready
      register: mk8s_status

    - name: Enable MicroK8s addons (dns, hostpath-storage)
      shell: microk8s enable dns hostpath-storage

    - name: Create argocd namespace
      shell: microk8s kubectl create namespace argocd
      ignore_errors: yes

    - name: Install ArgoCD
      shell: microk8s kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

    - name: Apply ArgoCD Application Manifest
      shell: microk8s kubectl apply -f /home/ubuntu/WhatTheFlag/argocd-app.yml
      ignore_errors: yes # Might fail if the file isn't there on the first run, but that's okay
